-- nothing worksss
-- vim.g.ackprg = 'rg --vimgrep --smart-case'
-- vim.keymap.set('n', '<C-F>', ':Ack!<space>')
--
-- cnoreabbrev ag Ack
-- cnoreabbrev aG Ack
-- cnoreabbrev Ag Ack
-- cnoreabbrev AG Ack
-- vim.cmd.inoreabbrev({ "<buffer>", "ag", "Ack" })
-- vim.cmd.inoreabbrev({ "<buffer>", "aG", "Ack" })
-- vim.cmd.inoreabbrev({ "<buffer>", "Ag", "Ack" })
-- vim.cmd.inoreabbrev({ "<buffer>", "AG", "Ack" })
